// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `admin.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.lpmas.admin.component;

public final class AdminServiceHolder extends Ice.ObjectHolderBase<AdminService>
{
    public
    AdminServiceHolder()
    {
    }

    public
    AdminServiceHolder(AdminService value)
    {
        this.value = value;
    }

    public void
    patch(Ice.Object v)
    {
        if(v == null || v instanceof AdminService)
        {
            value = (AdminService)v;
        }
        else
        {
            IceInternal.Ex.throwUOE(type(), v);
        }
    }

    public String
    type()
    {
        return _AdminServiceDisp.ice_staticId();
    }
}
