// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `admin.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.lpmas.admin.component;

public interface AdminService extends Ice.Object,
                                      _AdminServiceOperations, _AdminServiceOperationsNC
{
    public static final String ice_staticId = "::com::lpmas::admin::component::AdminService";

    public static final long serialVersionUID = -2036287955L;
}
